In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import duckdb

df_consumption = pd.read_csv("../../DataSources/fictional_households_electricity_consumption.csv")
df_price_2025 = pd.read_csv("../../DataSources/electricity_exchange_market_price_2025.csv", sep=";", decimal=',')
df_fixed = pd.read_csv("../../DataSources/fictional_vendor_fixed_pricing.csv", header = 1, usecols = [1, 2, 3, 4, 5])
df_exchange = pd.read_csv("../../DataSources/fictional_vendor_exchange_market_pricing.csv", header = 1, usecols = [1, 2, 3, 4, 5])

df_combined_price = pd.concat([
    pd.read_csv("../../DataSources/electricity_exchange_market_price_2023.csv", sep=";", decimal=','),
    pd.read_csv("../../DataSources/electricity_exchange_market_price_2024.csv", sep=";", decimal=','),
    pd.read_csv("../../DataSources/electricity_exchange_market_price_2025.csv", sep=";", decimal=',')
])

df_combined_price.to_csv("electricity_exchange_market_price_combined_raw.csv", index=False)

In [32]:
katse = pd.read_csv("../../DataSources/electricity_exchange_market_price_combined_raw.csv")

In [34]:
katse

,Periood,Börsihind senti/kWh (sisaldab käibemaksu),Börsihind senti/kWh (ei sisalda käibemaksu)
0,01.01.2023 00:00,0.58080,0.4840
1,01.01.2023 01:00,0.24120,0.2010
2,01.01.2023 02:00,0.16560,0.1380
3,01.01.2023 03:00,0.01080,0.0090
4,01.01.2023 04:00,0.00960,0.0080
...,...,...,...
26230,30.12.2025 20:00,11.88850,9.5875
26231,30.12.2025 21:00,11.52115,9.2912
26232,30.12.2025 22:00,10.29572,8.3030
26233,30.12.2025 23:00,10.42809,8.4097
26234,31.12.2025 00:00,9.57559,7.7222

In [35]:
df_price_2025

,Periood,Börsihind senti/kWh (sisaldab käibemaksu),Börsihind senti/kWh (ei sisalda käibemaksu)
0,01.01.2025 00:00,0.48922,0.4010
1,01.01.2025 01:00,0.59170,0.4850
2,01.01.2025 02:00,0.48190,0.3950
3,01.01.2025 03:00,0.46360,0.3800
4,01.01.2025 04:00,0.42212,0.3460
...,...,...,...
8732,30.12.2025 20:00,11.88850,9.5875
8733,30.12.2025 21:00,11.52115,9.2912
8734,30.12.2025 22:00,10.29572,8.3030
8735,30.12.2025 23:00,10.42809,8.4097
8736,31.12.2025 00:00,9.57559,7.7222

In [37]:
selected_rows = df_price_2025[df_price_2025['Periood'] == "26.10.2025 03:00"]
print(selected_rows)

               Periood  Börsihind senti/kWh (sisaldab käibemaksu)  \
7154  26.10.2025 03:00                                    2.48961
7155  26.10.2025 03:00                                    2.23820

      Börsihind senti/kWh (ei sisalda käibemaksu)
7154                                       2.0077
7155                                       1.8050

In [27]:
selected_rows_consumption = df_consumption[
    (df_consumption['timestamp'] == "2024-02-29 03:00:00") &
    (df_consumption['household_id'] == "EE_APT_001")
    ]
print(selected_rows_consumption)

       household_id            timestamp  consumption_kwh
305370   EE_APT_001  2024-02-29 03:00:00           0.0296

In [21]:
df_spot_2023 = pd.read_csv("../../DataSources/spot_pricing_2023_raw.csv", sep=";", decimal=',')
df_spot_2023

,Periood,Börsihind senti/kWh (sisaldab käibemaksu),Börsihind senti/kWh (ei sisalda käibemaksu)
0,01.01.2023 00:00,0.58080,0.484
1,01.01.2023 01:00,0.24120,0.201
2,01.01.2023 02:00,0.16560,0.138
3,01.01.2023 03:00,0.01080,0.009
4,01.01.2023 04:00,0.00960,0.008
...,...,...,...
8754,31.12.2023 19:00,11.90964,9.762
8755,31.12.2023 20:00,7.31878,5.999
8756,31.12.2023 21:00,5.00078,4.099
8757,31.12.2023 22:00,6.56726,5.383
8758,31.12.2023 23:00,6.76978,5.549

In [22]:
df_spot_2024 = pd.read_csv("../../DataSources/spot_pricing_2024_raw.csv", sep=";", decimal=',')
df_spot_2024

,Periood,Börsihind senti/kWh (sisaldab käibemaksu),Börsihind senti/kWh (ei sisalda käibemaksu)
0,01.01.2024 00:00,4.88122,4.001
1,01.01.2024 01:00,4.68114,3.837
2,01.01.2024 02:00,3.47212,2.846
3,01.01.2024 03:00,3.25252,2.666
4,01.01.2024 04:00,2.98656,2.448
...,...,...,...
8778,31.12.2024 19:00,10.84458,8.889
8779,31.12.2024 20:00,9.13414,7.487
8780,31.12.2024 21:00,6.60996,5.418
8781,31.12.2024 22:00,3.05976,2.508
8782,31.12.2024 23:00,0.96868,0.794

In [24]:
df_spot_2025 = pd.read_csv("../../DataSources/spot_pricing_2025_raw.csv", sep=";", decimal=',')
df_spot_2025

,Periood,Börsihind senti/kWh (sisaldab käibemaksu),Börsihind senti/kWh (ei sisalda käibemaksu)
0,01.01.2025 00:00,0.48922,0.4010
1,01.01.2025 01:00,0.59170,0.4850
2,01.01.2025 02:00,0.48190,0.3950
3,01.01.2025 03:00,0.46360,0.3800
4,01.01.2025 04:00,0.42212,0.3460
...,...,...,...
8754,31.12.2025 19:00,18.86133,15.2107
8755,31.12.2025 20:00,17.37426,14.0115
8756,31.12.2025 21:00,16.30941,13.1527
8757,31.12.2025 22:00,16.12496,13.0040
8758,31.12.2025 23:00,14.36385,11.5837

In [29]:
df_spot_pricing = pd.concat([
    pd.read_csv("../../DataSources/spot_pricing_2023_raw.csv", sep=";", decimal=','),
    pd.read_csv("../../DataSources/spot_pricing_2024_raw.csv", sep=";", decimal=','),
    pd.read_csv("../../DataSources/spot_pricing_2025_raw.csv", sep=";", decimal=',')
])

df_spot_pricing.to_csv("../../DataSources/spot_pricing_combined.csv", index=False)